### ISSUE TITLE
Tests is missing

### ISSUE THREAD

**Issue by alexted** [leosussan/fastapi-gino-arq-uvicorn#10]
What about tests?
Do you have a plans to add any test examples?

**Comment by leosussan** [comment]
I haven't had the opportunity just yet - but do have plans to do so (please feel free to submit a PR). 

I would prefer one of the following two options:
- _Recommended:_ HTTPX (an async replacement for `requests`) lets you [mount a ASGI/WSGI application](https://www.python-httpx.org/advanced/#calling-into-python-web-apps) directly to a client instance. ([API Reference](https://www.python-httpx.org/api/#client))
- FastAPI has a [test client](https://fastapi.tiangolo.com/tutorial/testing/) built into it, which directly subclasses [Starlette's TestClient](). To use this, you must add `requests` to your project.
